
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-ZipCode-Controller","number":38,"title":"Add ZipCode Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/38"},{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-ZipCode","number":37,"title":"Add ZipCode Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/37"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HomeController","number":32,"title":"Change Member and Repo in HomeController","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/32"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"Zeel-JokeQuery-Controller","number":28,"title":"Add Jokes Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/28"}]
