
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"Liam-Locations","number":21,"title":"Add Location Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/21"},{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-ZipCode-Controller","number":19,"title":"Add ZipCode Controller and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/19"},{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-ZipCode","number":18,"title":"Add ZipCode Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/18"}]
