
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"revert-18-Gretchen-ZipCode","number":34,"title":"Add ZipCode Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/34"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"Daoyi-HomeController","number":32,"title":"Change Member and Repo in HomeController","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/32"},{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"Owen-University-Controller","number":31,"title":"Add University Controller and Controller Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/31"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"Zeel-JokeQuery-Controller","number":28,"title":"Add Jokes Service and Controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/28"},{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"jamespflaging_tides","number":26,"title":"Add Tides Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/26"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"Zeel-JokeQuery","number":25,"title":"Add Joke Service and Test","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/25"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"Liam-Locations-Controller","number":24,"title":"Add Location Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/24"},{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"Owen-University","number":22,"title":"Add UniversityQueryService and UniversityQueryTests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/22"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"Liam-Locations","number":21,"title":"Add Location Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-1/pull/21"}]
